# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Scorer": "00_core.ipynb",
         "TiebreakScorer": "00_core.ipynb",
         "MatchTiebreakScorer": "00_core.ipynb",
         "GamePointScorer": "00_core.ipynb",
         "SetTracker": "00_core.ipynb",
         "MatchTracker": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://talksportsdata.github.io/tennisscorer/"

git_url = "https://github.com/talksportsdata/tennisscorer/tree/master/"

def custom_doc_links(name): return None
